import { describe, it, expect } from 'vitest';
import { buildChangelogUpdate } from '../../src/server';

// Regression test for the release_project_version Changelog bug (2026-07-23,
// observed on both Lib001 and SeaLeopard): the pipeline printed
// "Changelog.md: appended vX.Y.Z.W" while writing nothing to disk.
//
// Root cause (see buildChangelogUpdate's doc comment in src/server.ts): the
// old "ownership guard" checked for the literal text 'Auto-generated by
// `bump_project_version`', but the text this same tool actually seeded into
// new files was 'Auto-appended by `bump_project_version` on release.' --
// the two never matched, so the guard treated even the tool's own file as
// foreign and skipped writing. Separately, a genuinely hand-maintained
// Keep-a-Changelog file (Lib001's CHANGELOG.md) was never understood at all.

describe('buildChangelogUpdate', () => {
  it('seeds a fresh file in "ours" style when no Changelog.md exists yet', () => {
    const result = buildChangelogUpdate(null, '1.0.0.0', null, 'seed', ['initial import']);
    expect(result.status).toBe('written');
    expect(result.style).toBe('ours');
    expect(result.content).toContain('## v1.0.0.0 -- ');
    expect(result.content).toContain('- initial import');
  });

  it('appends to a Changelog.md that already uses "ours" style, even with the old intro wording', () => {
    // This is exactly SeaLeopard's real Changelog.md wording since its
    // v1.0.0.0 seed commit -- the case the old ownership-guard string
    // mismatch caused to silently no-op.
    const existing =
      '# Changelog\n\n' +
      'Auto-appended by `bump_project_version` on release. Newest entries at the top. Versions match\n' +
      'the value written to `Project Information.Version` and (once introduced) the runtime anchor\n' +
      '`_MCP_PROJECT_VERSION.sVersion`, so an entry here corresponds 1:1 to a value the running PLC will\n' +
      'report back via `read_running_version_online`.\n\n' +
      '## v1.3.0.0 -- 2026-07-23\n\n' +
      '- Furuno SCX-20 decoders added.\n';

    const result = buildChangelogUpdate(
      existing,
      '1.3.1.0',
      '1.3.0.0',
      'auto: revision',
      ['wired Furuno decoders into Can2_N2k_Control']
    );

    expect(result.status).toBe('written');
    expect(result.style).toBe('ours');
    expect(result.content).toBeDefined();
    const content = result.content!;

    // New entry must be newest-first: appears before the v1.3.0.0 heading.
    const newIdx = content.indexOf('## v1.3.1.0 -- ');
    const oldIdx = content.indexOf('## v1.3.0.0 -- ');
    expect(newIdx).toBeGreaterThan(-1);
    expect(oldIdx).toBeGreaterThan(-1);
    expect(newIdx).toBeLessThan(oldIdx);

    // Old entry content must survive untouched.
    expect(content).toContain('- Furuno SCX-20 decoders added.');
    expect(content).toContain('- wired Furuno decoders into Can2_N2k_Control');
  });

  it('appends to a Keep-a-Changelog file with an [Unreleased] section, inserting after it', () => {
    // Matches Lib001's real CHANGELOG.md structure.
    const existing =
      '# Changelog\n\n' +
      'All notable changes to the NMEA2000 MR Library are recorded here.\n' +
      'Format follows [Keep a Changelog](https://keepachangelog.com/); versioning is\n' +
      '`MAJOR.MINOR.PATCH.BUILD` per the README. Releases are tagged `vX.Y.Z.W`.\n\n' +
      '## [Unreleased]\n\n' +
      '## [0.20.2.2] - 2026-07-20\n\n' +
      '- Some prior fix.\n';

    const result = buildChangelogUpdate(existing, '0.21.0.0', '0.20.2.2', 'auto: minor', ['21 PGN decoders added']);

    expect(result.status).toBe('written');
    expect(result.style).toBe('keepachangelog');
    const content = result.content!;

    expect(content).toContain('## [Unreleased]');
    expect(content).toContain('## [0.21.0.0] - ');
    expect(content).toContain('## [0.20.2.2] - 2026-07-20');

    const unreleasedIdx = content.indexOf('## [Unreleased]');
    const newIdx = content.indexOf('## [0.21.0.0] - ');
    const oldIdx = content.indexOf('## [0.20.2.2] - 2026-07-20');
    expect(unreleasedIdx).toBeLessThan(newIdx);
    expect(newIdx).toBeLessThan(oldIdx);
    expect(content).toContain('- 21 PGN decoders added');
    expect(content).toContain('- Some prior fix.');
  });

  it('appends to a Keep-a-Changelog file with no [Unreleased] section', () => {
    const existing =
      '# Changelog\n\n' +
      'Format follows Keep a Changelog.\n\n' +
      '## [0.20.2.2] - 2026-07-20\n\n' +
      '- Some prior fix.\n';

    const result = buildChangelogUpdate(existing, '0.21.0.0', '0.20.2.2', 'auto: minor', ['21 PGN decoders added']);
    expect(result.status).toBe('written');
    expect(result.style).toBe('keepachangelog');
    const content = result.content!;
    const newIdx = content.indexOf('## [0.21.0.0] - ');
    const oldIdx = content.indexOf('## [0.20.2.2] - 2026-07-20');
    expect(newIdx).toBeGreaterThan(-1);
    expect(newIdx).toBeLessThan(oldIdx);
  });

  it('refuses to write into a genuinely unrecognized hand-maintained file (reports why, changes nothing)', () => {
    const existing =
      '# Changelog\n\n' +
      'This project tracks changes in prose, not headings.\n\n' +
      'July 2026: did some stuff.\n';
    const result = buildChangelogUpdate(existing, '1.0.0.0', null, 'auto: revision', ['x']);
    expect(result.status).toBe('skipped');
    expect(result.reason).toMatch(/not match a recognized heading style/i);
    expect(result.content).toBeUndefined();
  });

  it('works regardless of the Changelog.md vs CHANGELOG.md path casing passed in (case-insensitive FS)', () => {
    // buildChangelogUpdate itself is path-agnostic (pure string in/out); the
    // case-insensitivity is exercised at the appendChangelogEntry I/O layer,
    // but confirm the content-detection logic doesn't care about casing of
    // anything in the text either.
    const existing =
      '# CHANGELOG\n\n' +
      '## [Unreleased]\n\n' +
      '## [0.20.2.2] - 2026-07-20\n\n' +
      '- prior\n';
    const result = buildChangelogUpdate(existing, '0.21.0.0', null, 'auto: minor', ['new']);
    expect(result.status).toBe('written');
    expect(result.style).toBe('keepachangelog');
  });
});
