import { describe, it, expect } from 'vitest';
import { extractCustomLibraryMdSections } from '../../src/server';

// Regression test for the release_project_version library.md overwrite bug
// (found 2026-08-14 on Lib001): regenerateArtifact wrote renderLibraryMd's
// output straight over library.md, silently deleting any hand-maintained
// section -- in the wild, Lib001's "## Function Versions (per-object)"
// registry (100+ rows of per-FB version tracking). Regeneration must carry
// every non-generated section over to the fresh render.

const GENERATED_ONLY = `# Library inventory -- MR_Lib001.project

Auto-generated by \`list_project_libraries\`.

## Versions

| Field | Value |
|---|---|
| Project Information.Version | \`0.27.0.0\` |

## Devices

| Path | Type | ID | Version |
|---|---|---|---|
| \`Device\` | \`4102\` | \`0009\` | **\`3.5.19.0\`** |

**Total:** 58 library references across 2 library managers.

## Container: \`Application\` (libman: Library Manager) -- 44 refs

| name | namespace | kind | sys | effective |
|---|---|---|---|---|
| \`#Standard\` | \`Standard\` | placeholder | yes | Standard, 3.5.17.0 (System) |
`;

const CUSTOM_REGISTRY = `## Function Versions (per-object)

| Object | Kind | Path | Version |
|---|---|---|---|
| \`FB_N2kFischerPandaJ1939\` | FB | \`.../Fischer Panda J1939\` | \`0.0.7\` |
| \`FB_N2kNode\` | FB | \`Can/Dialects/N2k\` | \`0.2.1\` |`;

describe('extractCustomLibraryMdSections', () => {
  it('returns empty string when the file is fully generated', () => {
    expect(extractCustomLibraryMdSections(GENERATED_ONLY)).toBe('');
  });

  it('extracts a trailing hand-maintained section verbatim', () => {
    const existing = GENERATED_ONLY + '\n' + CUSTOM_REGISTRY + '\n';
    expect(extractCustomLibraryMdSections(existing)).toBe(CUSTOM_REGISTRY);
  });

  it('extracts multiple custom sections and skips generated ones between them', () => {
    const existing =
      GENERATED_ONLY + '\n## Notes\n\nHand-written note.\n\n' +
      '## Container: \`?\` (libman: Library Manager) -- 14 refs\n\n| a |\n|---|\n\n' +
      CUSTOM_REGISTRY + '\n';
    const out = extractCustomLibraryMdSections(existing);
    expect(out).toContain('## Notes');
    expect(out).toContain('Hand-written note.');
    expect(out).toContain('## Function Versions (per-object)');
    expect(out).not.toContain('## Container:');
  });

  it('handles CRLF line endings', () => {
    const existing = (GENERATED_ONLY + '\n' + CUSTOM_REGISTRY + '\n').replace(/\n/g, '\r\n');
    const out = extractCustomLibraryMdSections(existing);
    expect(out).toContain('## Function Versions (per-object)');
    expect(out).toContain('| \`FB_N2kNode\` | FB |');
  });
});
